name: CommandGUI
version: '1.0'
main: com.alfie51m.commandgui.CommandGui
api-version: '1.21'
commands:
  commandgui:
    description: Opens the Command GUI.
    permission: commandgui.commandgui
  cgreload:
    description: Reloads the CommandGUI configuration.
    permission: commandgui.reload
  cgbook:
    description: Gives the player a book to open the Command GUI.
    permission: commandgui.cgbook