name: CommandGUI
version: "3.1.0"
main: com.alfie51m.commandgui.CommandGui
api-version: '1.21'
commands:
  commandgui:
    description: Main command for the CommandGUI plugin.
    aliases: [cg]
    usage: "/commandgui [book|give <player>|reload]"
permissions:
  commandgui.use:
    description: Allows access to the /commandgui command and GUI.
    default: op
  commandgui.book:
    description: Allows access to /commandgui book to get a CommandGUI Book.
    default: op
  commandgui.give:
    description: Allows access to /commandgui give <player> to give the CommandGUI Book to another player.
    default: op
  commandgui.reload:
    description: Allows access to /commandgui reload to reload the configuration.
    default: op
