name: CommandGUI
version: '2.0'
main: com.alfie51m.commandgui.CommandGui
api-version: '1.21'
commands:
  commandgui:
    description: Opens the Command GUI.
  cgreload:
    description: Reloads the CommandGUI configuration.
  cgbook:
    description: Gives the player a book to open the Command GUI.
  cggive:
    description: Gives the custom Knowledge Book to another player.
    usage: /cggive <player>
permissions:
  commandgui.use:
    description: Allows access to the /commandgui command.
    default: op
  commandgui.reload:
    description: Allows access to the /cgreload command.
    default: op
  commandgui.book:
    description: Allows access to the /cgbook command.
    default: op
  commandgui.give:
    description: Allows access to the /cggive command and to give the Knowledge Book to other players.
    default: op